### ISSUE TITLE
Avoid word in Elements, avoid word pair, and contractions

### ISSUE THREAD

**Issue by minorhistory** [oxygenxml/dim#14]
Hi George, team, 

I was talking to George at Lavacon Dublin and he told me I should put in a request for this feature: 

What would really speed up the implementation of  my style guide in schematron is a hack that allows me to implement these items with the current set of rules, or adding new rules to implement the following: 

Avoid word in Elements - allows us to stop repeating a dita entry for the same word across all elements. 

Contractions - I cannot use AvoidWordInElement with contractions like can't don't etc, it breaks when I try and transform. It would be great if there were instructions on how to wrap the apostrophes so they don't break DIM. 

Avoid phrases in Elements. I want to target words, for example, "pull up" and post a message with the suggested word "lift". However, two words don't seem to work. 

I appreciate you taking the time to help with this. 

All the best, 

Melanie

**Comment by georgebina** [comment]
Solved the contractions part - we escape now `'` if found in parameter values when we generate the Schematron rules.

**Comment by georgebina** [comment]
Fot multiple elements, you can specify them separated with `|`, for example `title|p`.

**Comment by georgebina** [comment]
The generic rule was updated to support also phrases like "pull up".

**Comment by georgebina** [comment]
It will be great if you can test and confirm that all the reported issues are fixed.

**Comment by fergcondon** [comment]
Hi George,

I am involved on the same project as Melanie. Thank you for having a look at these issues. I have done some testing this morning on these updates.

The contractions update works. I can make rules for don't, doesn't etc.

The targeting of phrases like "pull up" also appears to be working. I have made rules for phrases like "log on", "sign on", etc and this appears to be working.

Your tip on separating elements with "|" also seems to be working. 

Thank you for resolving these!!!

Kind regards,
Fergal
