### ISSUE TITLE
AvoidWordInElement is case sensitive

### ISSUE THREAD

**Issue by minorhistory** [oxygenxml/dim#15]
Hi all, 

In my testing, I have found that I have to create an entry for each word with and without a capital letter. 

For example, I want to exclude the word "typically" but I must create two entries for "Typically" and "typically". 

Is there any way around this? 

Thanks, 

Melanie

**Comment by Schelmenzunft** [comment]
George, perhaps you could add a "lower-case" somewhere, so that one only has to create 1 entry with a capital letter ...

**Comment by georgebina** [comment]
The rule is case insensitive now.
