### ISSUE TITLE
conditional rules: if attribute = then apply rule

### ISSUE THREAD

**Issue by nozurbina** [oxygenxml/dim#7]
I'd like to be able to set conditional chains of rules. e.g if I insert a paragraph attribute is set to "twitter", then I want to trigger my restrictCharacter rule, but if it's not set, or set to something else, I'd like to not trigger it (or trigger another rule).

**Comment by georgebina** [comment]
For the parent element you can specify `p[@audience='twitter']` for example to apply that rule only when the audience attribute is set to twitter. Or you can say `p[contains(@audience,'twitter')]` to account for multiple audiences. Basically the `$parentElement` is expanded as the rule context, and any XPath expression that matches an element can be used there. You can also say `*[contains(@audience,'twitter')]` to match on any element that has the audience attribute containing 'twitter' and restrict its length to no more that 140 characters.

**Comment by nozurbina** [comment]
I will try that, but the UI should add parameters for parentAttrbiute, and then "whenAttributeEquals" and "whenAttributeContains" so that I don't have to type in the syntax. Ideally if we could check multiple attributes, great, but I need at least one for my projects today

**Comment by georgebina** [comment]
I am not sure if these should be added to the existing rules or we should offer a parallel set of rules in addition to the existing ones that offer also this attribute level filtering.

**Comment by nozurbina** [comment]
If parallel means that we can use the same messages and attribute settings
for various elements then parallel would be better.

On 25 March 2015 at 05:42, George Bina <notifications@github.com> wrote:

> I am not sure if these should be added to the existing rules or we should
> offer a parallel set of rules in addition to the existing ones that offer
> also this attribute level filtering.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oxygenxml/dim/issues/7#issuecomment-86010199>.
>



-- 
Noz

Content Strategist, urbinaconsulting.com <http://bit.ly/uc_site>
Co-Author of "Content Strategy: Connecting the dots between business, brand
and benefits <http://www.thecontentstrategybook.com>". In stores now:
thecontentstrategybook.com <http://www.thecontentstrategybook.com>

**Comment by georgebina** [comment]
No, I was thinking of a different rule, for example `restrictWordsAdvanced`, `restrictWords-filtered`, `restrictWords-whenAttribute` or something like that, and this new rule will have additional attribute related filter parameters.

**Comment by georgebina** [comment]
Thinking more about this, then I think it will be possible to have also a solution that will work for any element parameter. This can be implemented using a custom editor for the parameter value that will present a nice way of specifying attribute filters and it will build the actual parameter value when the editing session is finalized.

**Comment by nozurbina** [comment]
That sounds best. I think multi-select is the way forward. Allow me to
specify a rule then allow me to add as many elements as I want, and then
attributes to those elements.

On 25 March 2015 at 07:34, George Bina <notifications@github.com> wrote:

> Thinking more about this, then I think it will be possible to have also a
> solution that will work for any element parameter. This can be implemented
> using a custom editor for the parameter value that will present a nice way
> of specifying attribute filters and it will build the actual parameter
> value when the editing session is finalized.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oxygenxml/dim/issues/7#issuecomment-86052103>.
>



-- 
Noz

Content Strategist, urbinaconsulting.com <http://bit.ly/uc_site>
Co-Author of "Content Strategy: Connecting the dots between business, brand
and benefits <http://www.thecontentstrategybook.com>". In stores now:
thecontentstrategybook.com <http://www.thecontentstrategybook.com>

**Comment by georgebina** [comment]
Yes, basically when you have en element parameter then you can use
`element` - to match a single element
`element[@attribute='value']` - to match an element with an attribute equal to a specified value
`element[contains(@attribute='value')]` - to match an element with an attribute containing a specified value
`element1 | element2 | element3` - to match any of element1, element2 or element3
`element1[@attribute='value'] | element2[contains(@attribute='value')] | element3` - to match any of element1 that has an attribute with a specified value, element2 that has an attribute containing a specified value or element3
etc.
All we need is a visual builder for these patterns rather than generating many rules to cover each situation.

**Comment by nozurbina** [comment]
I would be happy to discuss designs. Are there any other similar rules
builders which are well known and successful we could look at?

On 25 March 2015 at 07:52, George Bina <notifications@github.com> wrote:

> Yes, basically when you have en element parameter then you can use
> element - to match a single element
> element[@attribute='value'] - to match an element with an attribute equal
> to a specified value
> element[contains(@attribute='value')] - to match an element with an
> attribute containing a specified value
> element1 | element2 | element3 - to match any of element1, element2 or
> element3
> element1[@attribute='value'] | element2[contains(@attribute='value')] |
> element3 - to match any of element1 that has an attribute with a
> specified value, element2 that has an attribute containing a specified
> value or element3
> etc.
> All we need is a visual builder for these patterns rather than generating
> many rules to cover each situation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oxygenxml/dim/issues/7#issuecomment-86065226>.
>



-- 
Noz

Content Strategist, urbinaconsulting.com <http://bit.ly/uc_site>
Co-Author of "Content Strategy: Connecting the dots between business, brand
and benefits <http://www.thecontentstrategybook.com>". In stores now:
thecontentstrategybook.com <http://www.thecontentstrategybook.com>

**Comment by georgebina** [comment]
None I know of. We need a visual XPath expression builder that we can plug into the oXygen Author view to edit the match expression (this is what the element parameter translates to in the actual result Schematron rule).

**Comment by nozurbina** [comment]
I was thinking more generally about filter, search or query builders.
What's important is that there is a 2 level model (elements/attributes) and
the user needs to be able to flexibly create sets of matching rules for
different combinations. I will try to think of use cases
