### ISSUE TITLE
Mysterious rules

### ISSUE THREAD

**Issue by nozurbina** [oxygenxml/dim#9]
I am getting rules that I can't find the source of in the informationModel bookmap for example: concepts require prolog, and topic information types are not allowed at all.

**Comment by georgebina** [comment]
Hi Noz,

Each rule has also a `see` attribute that will point to the topic it comes from. Just click on the URL (the book icon) of the error message and that will take you to the topic it comes from. If you open the topic source then you should find the rule there.

Regards,
George

**Comment by georgebina** [comment]
I updated the test project to use the catalog file found in `[DIM]/info-model/rules/catalog.xml` so the links to styleguide will work correctly. The `@see` attribute uses something like `http://exmple.com/styleguide/...` for references to style guide topics and these are resolved though that catalog file to a local copy of the style guide WebHelp output.

**Comment by nozurbina** [comment]
I found out that there was a rules link written into the header pointing to
an old file. It was validating against that instead of the file I had
modified. The project should use either links in the topic or the project
settings but not both.  It makes things confusing.

**Comment by georgebina** [comment]
I do not understand your last comment... do you mean you had an `<?xml-model ...` processing instruction pointing to a Schematron schema and also the Schematron schema added as part of the DITA validation scenario?
If that is the case, yes, probably you should keep the files clean and just set whatever schemas you want to use for your documents in the DITA validation scenario.
